#!/bin/bash
## test-pipeline-standard
## version 0.0.1 - initial
##################################################
upper() { { local str ; read str ; }
echo error in upper 1>&2
echo ${str^^}
}
lower() { { local str ; read str ; }
echo error in lower 1>&2
echo ${str,,}
}
arg-to-var() { { local str ; read str ; }
# echo arg is $str
# echo ${str,,} 1>&2
echo ${str^^} 1>&2
}
std-err-to-variable() { { local str ; read str ; }
echo ${str,,} 
# echo ${str^^}
# echo std-err is $str
# echo ${str,,} 
}

test-pipeline-standard() {
echo ${@} | arg-to-var |& std-err-to-variable
}
##################################################

##################################################
test-pipeline-standard ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 23 Jul 2019 13:28:31 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
# { ps -p "$proc" | fgrep "$proc";} >/dev/null 2>&1
# { ./TrialBalance.sh | fgrep hello;}
# { /usr/bin/time ./TrialBalance.sh 0 0 |& grep 0 ;}
# { /usr/bin/time ./TrialBalance.sh 0 0 |& grep 0 ;} >/dev/null
#  { /usr/bin/time ./TrialBalance.sh 0 0 1>&2 ;} >/dev/null
#  { /usr/bin/time ./TrialBalance.sh 0 0  ;} >/dev/null
#  ({ /usr/bin/time ./TrialBalance.sh 0 0  ;} >/dev/null) | (read foo; echo $foo)
#  { /usr/bin/time ./TrialBalance.sh 0 0 1>/dev/null} | (read foo; echo $foo)
# { /usr/bin/time -f "%e" ./TrialBalance.sh 0 0 1>/dev/null} | ({read foo; echo hello $foo })
#  { /usr/bin/time -f "%e" ./TrialBalance.sh 0 0 1>/dev/null} | ({read foo; echo hello $foo })
